name: BanAnnouncer
author: Tini
main: me.tini.announcer.bukkit.BanAnnouncerBukkit
version: ${project.version}
depend: [Spicord]
softdepend: [AdvancedBan, LiteBans, MaxBansPlus, Essentials, BetterJails]
description: Announce the punishments on your Discord server
api-version: 1.13

commands:
  banannouncer-reload:
    aliases: [ bareload ]
