name: BanAnnouncer
author: Tini
main: me.tini.announcer.plugin.bukkit.BanAnnouncerBukkit
version: ${project.version}
depend: [Spicord]
softdepend:
 - AdvancedBan
 - LiteBans
 - LibertyBans
 - MaxBansPlus
 - Essentials
 - BetterJails
description: Announce the punishments on your Discord server
api-version: 1.13

commands:
  banannouncer-reload:
    aliases: [ bareload ]
